### ISSUE TITLE
[ Nayeon - Main ] image slider 기능 구현

### ISSUE THREAD

**Issue by NYeonK** [TeamPiickle/pre-task-client#2]
## 종류

ISSUE 종류를 선택하세요 (`[ ]` 안에 `x` 표시, `[x]`)

- [ ] Refactor (리모델링 재개발)
- [ ] Fix (내가 해결해주지)
- [ ] Bug (삐용삐용 큰일 났어 / 질문)
- [x] Feature (제가 해냈습니다)

## 내용

- Image slider 기능 구현

## 체크리스트

- [x] Assignees, Labels, MileStone 달기
- [x] 컨벤션 지키기
- [x] < (이전), >(다음) 버튼 클릭으로 슬라이드 이미지 전환하기
- [x] 터치로 슬라이드 이미지 전환하기 (모바일)

**Comment by joohaem** [comment]
https://react-slick.neostack.com/
이거 참고해서 짜면 될거야!

```
$ yarn add react-slick
```
하고 거의 그대로 따라쳐도 될걸!! (styled-components 로 css 작성하고)
